# Generated by Django 4.2.7 on 2023-12-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('id', models.IntegerField(help_text='Side ID', primary_key=True, serialize=False)),
                ('side_url', models.CharField(help_text='Teksten som vises i url-ene', max_length=100)),
                ('title', models.CharField(help_text='Sidetittel som vises øverst på siden', max_length=120)),
                ('content', models.TextField()),
                ('page_type', models.CharField(choices=[('about', 'ABOUT'), ('contact', 'CONTACT')], default='about', max_length=7)),
            ],
            options={
                'verbose_name': 'Standard sidetype',
                'verbose_name_plural': 'Standard sidetyper',
                'ordering': ['title'],
            },
        ),
    ]
