# Generated by Django 4.2.7 on 2024-01-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Julekurv',
            fields=[
                ('id', models.IntegerField(help_text='Julekurv ID', primary_key=True, serialize=False)),
                ('url_name', models.CharField(help_text='Teksten som vises i url-ene', max_length=100)),
                ('name', models.CharField(help_text='Navnet på julekurven', max_length=120)),
                ('about', models.TextField()),
                ('image_julekurv', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Julekurv',
                'verbose_name_plural': 'Julekurver',
                'ordering': ['name'],
            },
        ),
    ]
