# Generated by Django 3.1.4 on 2024-10-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_julekurv_image_julekurv'),
    ]

    operations = [
        migrations.AddField(
            model_name='julekurv',
            name='image_julekurv_mal',
            field=models.FileField(blank=True, null=True, upload_to='frontend/static/images/julekurver/mal'),
        ),
    ]
