# Generated by Django 3.1.4 on 2024-10-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20241004_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='julekurv',
            name='image_julekurv',
            field=models.ImageField(upload_to='julekurver/flettet'),
        ),
        migrations.AlterField(
            model_name='julekurv',
            name='image_julekurv_mal',
            field=models.FileField(blank=True, null=True, upload_to='julekurver/mal'),
        ),
    ]
