# Generated by Django 5.1.1 on 2024-10-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20241004_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='julekurv',
            name='difficulty_level',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, help_text='Vanskelighetsgrad fra 1 til 10'),
        ),
        migrations.AddField(
            model_name='julekurv',
            name='hide_kurv',
            field=models.BooleanField(default=False, help_text='Skjuler julekurven hvis valgt'),
        ),
    ]
