# Generated by Django 5.1.1 on 2024-10-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_hjertekurv_kurvcategory_delete_julekurv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hjertekurv',
            name='image_hjertekurv_mal2',
            field=models.FileField(blank=True, help_text='Noen kurver har to forskjellige maler', null=True, upload_to='hjertekurv/mal'),
        ),
        migrations.AlterField(
            model_name='hjertekurv',
            name='image_hjertekurv',
            field=models.ImageField(help_text='Bilde av ferdig flettet kurv', upload_to='hjertekurv/flettet'),
        ),
        migrations.AlterField(
            model_name='hjertekurv',
            name='image_hjertekurv_mal',
            field=models.FileField(blank=True, help_text='Malen til kurven', null=True, upload_to='hjertekurv/mal'),
        ),
    ]
