# Generated by Django 3.1.4 on 2024-10-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_hjertekurv_image_hjertekurv_mal2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hjertekurv',
            name='download_mal',
            field=models.ImageField(blank=True, help_text='Bilde av mal som skal kunne lastes ned av bruker (PDF)', null=True, upload_to='hjertekurv/download'),
        ),
        migrations.AddField(
            model_name='hjertekurv',
            name='hjertekurv_image',
            field=models.FileField(blank=True, help_text='Bilde (svg) av ferdig flettet kurv', null=True, upload_to='hjertekurv/flettet'),
        ),
        migrations.AlterField(
            model_name='kurvcategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
