# Generated by Django 3.1.4 on 2024-10-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20241028_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hjertekurv',
            name='download_mal',
            field=models.FileField(blank=True, help_text='Bilde av mal som skal kunne lastes ned av bruker (PDF)', null=True, upload_to='hjertekurv/download'),
        ),
    ]
