# Generated by Django 3.1.4 on 2024-11-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20241028_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Tilbakemelding meldt inn')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Tilbakemelding',
                'verbose_name_plural': 'Tilbakemeldinger',
            },
        ),
    ]
