# Generated by Django 3.1.4 on 2024-11-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hjertekurv',
            name='image_hjertekurv',
        ),
    ]
