# Generated by Django 3.1.4 on 2024-11-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_hjertekurv_image_hjertekurv'),
    ]

    operations = [
        migrations.AddField(
            model_name='hjertekurv',
            name='difficulty_level_scissor',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, help_text='Vanskelighetsgrad (klipping) fra 1 til 10'),
        ),
        migrations.AlterField(
            model_name='hjertekurv',
            name='difficulty_level',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, help_text='Vanskelighetsgrad (fletting) fra 1 til 10'),
        ),
    ]
