# Generated by Django 3.1.4 on 2024-11-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20241108_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hjertekurv',
            old_name='difficulty_level',
            new_name='Vanskelighetsgrad: Fletting',
        ),
        migrations.RenameField(
            model_name='hjertekurv',
            old_name='difficulty_level_scissor',
            new_name='Vanskelighetsgrad: Klipping',
        ),
    ]
