# Generated by Django 3.1.4 on 2024-11-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20241116_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hjertekurv',
            name='Vanskelighetsgrad: Fletting',
        ),
        migrations.RemoveField(
            model_name='hjertekurv',
            name='Vanskelighetsgrad: Klipping',
        ),
        migrations.AddField(
            model_name='hjertekurv',
            name='difficulty_fletting',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, help_text='Vanskelighetsgrad (fletting) fra 1 til 10', verbose_name='Vanskelighetsgrad - Fletting'),
        ),
        migrations.AddField(
            model_name='hjertekurv',
            name='difficulty_klipping',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, help_text='Vanskelighetsgrad (klipping) fra 1 til 10', verbose_name='Vanskelighetsgrad - Klipping'),
        ),
        migrations.AlterField(
            model_name='hjertekurv',
            name='about',
            field=models.TextField(verbose_name='Info om kurven'),
        ),
        migrations.AlterField(
            model_name='hjertekurv',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Kategorier til hjertekurven', related_name='hjertekurver', to='api.KurvCategory', verbose_name='Kategorier'),
        ),
        migrations.AlterField(
            model_name='hjertekurv',
            name='download_mal',
            field=models.FileField(blank=True, help_text='Bilde av mal som skal kunne lastes ned av bruker (PDF)', null=True, upload_to='hjertekurv/download', verbose_name='Nedlastbar mal (pdf)'),
        ),
        migrations.AlterField(
            model_name='hjertekurv',
            name='hide_kurv',
            field=models.BooleanField(default=False, help_text='Skjuler hjertekurven hvis valgt', verbose_name='Skjul kurv'),
        ),
        migrations.AlterField(
            model_name='hjertekurv',
            name='hjertekurv_image',
            field=models.FileField(blank=True, help_text='Bilde (svg) av ferdig flettet kurv', null=True, upload_to='hjertekurv/flettet', verbose_name='Bilde av kurv (svg)'),
        ),
        migrations.AlterField(
            model_name='hjertekurv',
            name='image_hjertekurv_mal',
            field=models.FileField(blank=True, help_text='Malen til kurven', null=True, upload_to='hjertekurv/mal', verbose_name='Mal - 1'),
        ),
        migrations.AlterField(
            model_name='hjertekurv',
            name='image_hjertekurv_mal2',
            field=models.FileField(blank=True, help_text='Noen kurver har to forskjellige maler', null=True, upload_to='hjertekurv/mal', verbose_name='Mal - 2 (om behov)'),
        ),
        migrations.AlterField(
            model_name='hjertekurv',
            name='name',
            field=models.CharField(help_text='Navnet på hjertekurven', max_length=120, verbose_name='Navnet på kurven (tittel)'),
        ),
        migrations.AlterField(
            model_name='hjertekurv',
            name='related_kurver',
            field=models.ManyToManyField(blank=True, help_text='Relaterte hjertekurven', related_name='related_to', to='api.Hjertekurv', verbose_name='Relaterte kurver'),
        ),
        migrations.AlterField(
            model_name='hjertekurv',
            name='url_name',
            field=models.CharField(help_text='Teksten som vises i url-ene', max_length=100, verbose_name='Navnet på url-en'),
        ),
    ]
