# Generated by Django 3.1.4 on 2024-11-16 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20241116_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='hjertekurv',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Dato når hjertekurven ble opprettet', verbose_name='Opprettet dato'),
            preserve_default=False,
        ),
    ]
