# Generated by Django 3.1.4 on 2024-11-16 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_hjertekurv_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hjertekurv',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Dato når hjertekurven ble opprettet', verbose_name='Opprettet dato'),
        ),
    ]
