# Generated by Django 3.1.4 on 2025-01-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_visitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='content_en',
            field=models.TextField(default='', help_text='Content in English', null=True),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='content',
            field=models.TextField(help_text='Innhold på norsk'),
        ),
    ]
