# Generated by Django 3.1.4 on 2025-01-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20250106_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='hjertekurv',
            name='about_en',
            field=models.TextField(default='', null=True, verbose_name='Info om kurven (engelsk)'),
        ),
        migrations.AddField(
            model_name='hjertekurv',
            name='name_en',
            field=models.CharField(default='', help_text='Navnet på hjertekurven (engelsk)', max_length=120, null=True, verbose_name='Navnet på kurven (engelsk)'),
        ),
    ]
