# Generated by Django 3.1.4 on 2025-01-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20250108_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurvcategory',
            name='name_en',
            field=models.CharField(default='', help_text='Navnet på kategorien (engelsk)', max_length=100, null=True),
        ),
    ]
