name: Django CI

on:
  push:
  pull_request:

jobs:
  django_job:
    name: Test Django
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/backend/requirements.txt
        
  frontend_job:
    name: Test Frontend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: |
        cd src/frontend
        npm i

    - name: Run Build
      run: |
        cd src/frontend
        npm run build

    - name: Run ESLint
      run: |
        cd src/frontend
        npm run lint

    - name: Run Prettier Check
      run: |
        cd src/frontend
        npm run format:check
